root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./src/*.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", "static"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

[proxy]
  enabled = true
  proxy_port = 8000
  app_port = 1337
